name = "xingshuang-pro"
main = "worker.js"
compatibility_date = "2026-01-01"
[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "xingshuang-pro"
database_id = "3ba172d9-29fb-4430-8cf7-59a19d8ee665"
[vars]
BOT_TOKEN = ""
WEBHOOK_SECRET = ""
SUPER_ADMINS = ""
WEBAPP_URL = ""
